# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'añadir_libro.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Aniadir_Libro(object):
    def setupUi(self, Aniadir_Libro):
        Aniadir_Libro.setObjectName("Aniadir_Libro")
        Aniadir_Libro.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pixil-frame-0 (4).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Aniadir_Libro.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Aniadir_Libro)
        self.label.setGeometry(QtCore.QRect(130, 30, 161, 21))
        self.label.setObjectName("label")
        self.label_mensaje = QtWidgets.QLabel(Aniadir_Libro)
        self.label_mensaje.setGeometry(QtCore.QRect(35, 200, 341, 20))
        self.label_mensaje.setText("")
        self.label_mensaje.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mensaje.setObjectName("label_mensaje")
        self.layoutWidget = QtWidgets.QWidget(Aniadir_Libro)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 240, 158, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.aniadir_aceptar = QtWidgets.QPushButton(self.layoutWidget)
        self.aniadir_aceptar.setObjectName("aniadir_aceptar")
        self.horizontalLayout.addWidget(self.aniadir_aceptar)
        self.aniadir_cerrar = QtWidgets.QPushButton(self.layoutWidget)
        self.aniadir_cerrar.setObjectName("aniadir_cerrar")
        self.horizontalLayout.addWidget(self.aniadir_cerrar)
        self.layoutWidget1 = QtWidgets.QWidget(Aniadir_Libro)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 70, 301, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_titulo = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_titulo.sizePolicy().hasHeightForWidth())
        self.line_titulo.setSizePolicy(sizePolicy)
        self.line_titulo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.line_titulo.setDragEnabled(False)
        self.line_titulo.setReadOnly(False)
        self.line_titulo.setObjectName("line_titulo")
        self.verticalLayout_2.addWidget(self.line_titulo)
        self.line_autor = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_autor.sizePolicy().hasHeightForWidth())
        self.line_autor.setSizePolicy(sizePolicy)
        self.line_autor.setObjectName("line_autor")
        self.verticalLayout_2.addWidget(self.line_autor)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_2.addWidget(self.spinBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(Aniadir_Libro)
        self.aniadir_cerrar.clicked.connect(Aniadir_Libro.close)
        QtCore.QMetaObject.connectSlotsByName(Aniadir_Libro)
        Aniadir_Libro.setTabOrder(self.aniadir_aceptar, self.aniadir_cerrar)

    def retranslateUi(self, Aniadir_Libro):
        _translate = QtCore.QCoreApplication.translate
        Aniadir_Libro.setWindowTitle(_translate("Aniadir_Libro", "AÑADIR LIBRO"))
        self.label.setText(_translate("Aniadir_Libro", "Introduzca los datos del libro"))
        self.aniadir_aceptar.setText(_translate("Aniadir_Libro", "Aceptar"))
        self.aniadir_cerrar.setText(_translate("Aniadir_Libro", "Cancelar"))
        self.label_2.setText(_translate("Aniadir_Libro", "Título (Obligatorio): "))
        self.label_3.setText(_translate("Aniadir_Libro", "Autor:"))
        self.label_4.setText(_translate("Aniadir_Libro", "Género:"))
        self.label_5.setText(_translate("Aniadir_Libro", "Puntuación (1-10):"))

